
POST http://localhost:3000/api/events-login
Content-Type : application/json

{
    "title": "evento numero 1",
    "description": "este es el evento numero 1" ,
    "dates": [ "2021-07-28T22:00:00.081+00:00" , "2021-07-29T22:00:00.081+00:00"],
    "place": "en la plaza 25 de mayo",
    "image": "http://#"
}

###


POST http://localhost:3000/api/events-login
Content-Type : application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGM5MTk0OGI5NWRjMmMyYzg0OTM1OCIsInVzZXJuYW1lIjoiYXpheGhlbCIsImlhdCI6MTYyODIxMzY3NSwiZXhwIjoxNjI4ODE4NDc1fQ.4pwJgRqT6elnTK05A0-3Or8eVTTnNt1DPAWEO6fCMqM

{
    "title" : "Fiesta Nacional del Poncho 35º edición", 
    "description" : "descripcion", 
    "dates" : ["2022-11-28T22:44:33.081+00:00","2023-11-28T22:44:33.081+00:00","2021-10-28T22:44:33.081+00:00","2024-04-28T22:44:33.081+00:00"], 
    "place" : "Catamarca_Capital", 
    "image" : "http://#"
}


###

// fecha no valida
POST http://localhost:3000/api/events-login
Content-Type : application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGM5MTk0OGI5NWRjMmMyYzg0OTM1OCIsInVzZXJuYW1lIjoiYXpheGhlbCIsImlhdCI6MTYyODIxMzY3NSwiZXhwIjoxNjI4ODE4NDc1fQ.4pwJgRqT6elnTK05A0-3Or8eVTTnNt1DPAWEO6fCMqM

{
    "title" : "PONCHO 45", 
    "description" : "festival en el que se venden variadas artesanias", 
    "dates" : ["2022-03-05T22:44:33.081+00:00", "2000-02-10T22:44:33.081+00:00", "2021-12-20T22:44:33.081+00:00"], 
    "place" : "frente del estadio", 
    "image" : "http://#"
}