GET http://localhost:3000/api/events-login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGM5MTk0OGI5NWRjMmMyYzg0OTM1OCIsInVzZXJuYW1lIjoiYXpheGhlbCIsImlhdCI6MTYyODIxMzY3NSwiZXhwIjoxNjI4ODE4NDc1fQ.4pwJgRqT6elnTK05A0-3Or8eVTTnNt1DPAWEO6fCMqM